import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";

import Login from "../components/Login";

type Props = {};

const index = (props: Props) => {
  const [isAuthenticated, setIsAuthenticated] = useState(false);

  if (!isAuthenticated) {
    return <Login />;
  }
  return (
    <div className="h-screen">
      <Head>
        <title>Archlight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="text-2xl underline font-bold ">index</div>
      </main>
    </div>
  );
};

export default index;
